name: CD - Deploy to EC2 (Main only)

on:
  workflow_run:
    workflows: ["CI - Main Branch (Build & Push)"]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/alz-api:latest
            docker stop alz-api || true
            docker rm alz-api || true
            docker run -d --name alz-api -p 80:8000 ${{ secrets.DOCKER_USERNAME }}/alz-api:latest