name: CI - Dev Branches (Build Only)

on:
  push:
    branches-ignore:
      - main

jobs:
  build-only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download model weights from GitHub Release
        run: |
          curl -L -o models.zip https://github.com/SergeAlhalbi/alz-api/releases/download/v1.0-models/models.zip
          mkdir -p outputs
          unzip -q models.zip -d outputs/
          rm models.zip

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false